-- MySQL Script generated by MySQL Workbench
-- Wed Jan  9 22:26:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `role_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organization` (
  `organization_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`organization_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(15) NOT NULL,
  `last_name` VARCHAR(15) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `role_id` INT NOT NULL,
  `organization_id` INT NULL,
  `account_join_date` DATETIME NOT NULL,
  `account_delete_date` DATETIME NULL,
  `last_signin` DATETIME NOT NULL,
  `activation_datetime` DATETIME NULL,
  `unsuccessful_attempt` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `role_id_idx` (`role_id` ASC),
  UNIQUE INDEX `organization_id_UNIQUE` (`organization_id` ASC),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organization_id`
    FOREIGN KEY (`organization_id`)
    REFERENCES `mydb`.`Organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discount` (
  `discount_id` INT NOT NULL,
  `begin_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `discount_value` DECIMAL(19,4) NULL,
  `discount_percentage` DECIMAL(9,4) NULL,
  `last_updated` DATETIME NULL,
  `discount_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Approved_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Approved_Product` (
  `approved_product_id` INT NOT NULL,
  `approved_by` INT NOT NULL,
  `approved_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`approved_product_id`),
  INDEX `approved_by_user_id_approved_product_fk_idx` (`approved_by` ASC),
  CONSTRAINT `approved_product_product_id_fk`
    FOREIGN KEY (`approved_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `approved_by_user_id_approved_product_fk`
    FOREIGN KEY (`approved_by`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `SKU` VARCHAR(8) NULL,
  `UPC` VARCHAR(12) NULL,
  `discount_id` INT NULL,
  `approved_product_id` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `user_id_product_id_idx` (`user_id` ASC),
  INDEX `product_discount_id_fk_idx` (`discount_id` ASC),
  INDEX `product_approved_product_fk_idx` (`approved_product_id` ASC),
  CONSTRAINT `product_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_discount_id_fk`
    FOREIGN KEY (`discount_id`)
    REFERENCES `mydb`.`Discount` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_approved_product_fk`
    FOREIGN KEY (`approved_product_id`)
    REFERENCES `mydb`.`Approved_Product` (`approved_product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Stock` (
  `product_stock_id` INT NOT NULL,
  `stock_level` INT NOT NULL,
  `last_updated` DATETIME NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`product_stock_id`),
  INDEX `product_id_product_stock_idx` (`product_id` ASC),
  CONSTRAINT `product_id_product_stock`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tax_Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tax_Rate` (
  `tax_rate_id` INT NOT NULL,
  `rate` DOUBLE NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `province_state` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`tax_rate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipping_Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipping_Rate` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`General_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`General_Category` (
  `general_category_id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`general_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale_Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale_Transaction` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_Detail` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Rating` (
  `product_rating_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `review` VARCHAR(200) NOT NULL,
  `review_posted` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`product_rating_id`),
  INDEX `user_id_product_rating_id_idx` (`user_id` ASC),
  INDEX `product_rating_product_id_idx` (`product_id` ASC),
  CONSTRAINT `user_id_product_rating_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_rating_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_QA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_QA` (
  `product_qa_id` INT NOT NULL,
  `question` VARCHAR(150) NOT NULL,
  `answer` VARCHAR(150) NULL,
  `asked_by` INT NOT NULL,
  `answered_by` INT NULL,
  `asked_datetime` DATETIME NOT NULL,
  `answered_datetime` DATETIME NULL,
  `Product_QAcol` VARCHAR(45) NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`product_qa_id`),
  INDEX `user_id_product_qa_asked_idx` (`asked_by` ASC),
  INDEX `answered_by_product_qa_idx` (`answered_by` ASC),
  INDEX `product_qa_product_id_idx` (`product_id` ASC),
  CONSTRAINT `asked_by_product_qa`
    FOREIGN KEY (`asked_by`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answered_by_product_qa`
    FOREIGN KEY (`answered_by`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_qa_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`History_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`History_Log` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Details` (
  `user_details_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `street_number` INT NOT NULL,
  `street_name` VARCHAR(20) NOT NULL,
  `city` VARCHAR(15) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `postal_code` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`user_details_id`),
  INDEX `user_user_details_idx` (`user_id` ASC),
  CONSTRAINT `user_user_details`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PayPal_Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PayPal_Billing` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipping_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipping_Address` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Billing_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Billing_Address` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subcategory` (
  `subcategory_id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`subcategory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`General_Category_Subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`General_Category_Subcategory` (
  `general_category_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  INDEX `general_category_id_fk_idx` (`general_category_id` ASC),
  INDEX `subcategory_id_fk_idx` (`subcategory_id` ASC),
  CONSTRAINT `general_category_id_fk`
    FOREIGN KEY (`general_category_id`)
    REFERENCES `mydb`.`General_Category` (`general_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategory_id_fk`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`Subcategory` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subcategory_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subcategory_Types` (
  `subcategory_types_id` INT NOT NULL,
  `name` VARCHAR(25) NULL,
  PRIMARY KEY (`subcategory_types_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategory_subcategory_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategory_subcategory_types` (
  `subcategory_id` INT NOT NULL,
  `subcategory_types_id` INT NOT NULL,
  INDEX `subcategory_id_fk_idx` (`subcategory_id` ASC),
  INDEX `subcategory_types_id_idx` (`subcategory_types_id` ASC),
  CONSTRAINT `subcategory_id_fk`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`Subcategory` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategory_types_id`
    FOREIGN KEY (`subcategory_types_id`)
    REFERENCES `mydb`.`Subcategory_Types` (`subcategory_types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_subcategory_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_subcategory_types` (
  `product_id` INT NOT NULL,
  `subcategory_types_id` INT NOT NULL,
  INDEX `product_id_fk_idx` (`product_id` ASC),
  INDEX `subcategory_types_id_fk_idx` (`subcategory_types_id` ASC),
  CONSTRAINT `product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategory_types_id_fk`
    FOREIGN KEY (`subcategory_types_id`)
    REFERENCES `mydb`.`Subcategory_Types` (`subcategory_types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favourite_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favourite_Product` (
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `user_id_fk_idx` (`user_id` ASC),
  INDEX `product_id_fk_idx` (`product_id` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favourite_User_Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favourite_User_Organization` (
  `user_id` INT NOT NULL,
  `organization_id` INT NOT NULL,
  INDEX `user_id_fk_idx` (`user_id` ASC),
  INDEX `organization_id_fk_idx` (`organization_id` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organization_id_fk`
    FOREIGN KEY (`organization_id`)
    REFERENCES `mydb`.`Organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attributes` (
  `attribute_id` INT NOT NULL,
  `attribute_name` VARCHAR(20) NOT NULL,
  `value` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Attributes` (
  `product_id` INT NOT NULL,
  `attribute_id` INT NOT NULL,
  INDEX `product_id_idx` (`product_id` ASC),
  INDEX `attribute_id_idx` (`attribute_id` ASC),
  CONSTRAINT `product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute_id`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `mydb`.`Attributes` (`attribute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Default_Shirt_Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Default_Shirt_Size` (
  `default_shirt_sizes` INT NOT NULL,
  `name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`default_shirt_sizes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Default_Colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Default_Colour` (
  `default_colour_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `rgb` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`default_colour_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Default_Pant_Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Default_Pant_Size` (
  `default_pant_size` INT NOT NULL,
  `waist` INT NOT NULL,
  `inseam` INT NOT NULL,
  PRIMARY KEY (`default_pant_size`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Default_Shoe_Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Default_Shoe_Size` (
  `default_shoe_size_id` INT NOT NULL,
  `size` INT NOT NULL,
  `country` VARCHAR(20) NULL,
  PRIMARY KEY (`default_shoe_size_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Price` (
  `price_id` INT NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `price_start_date` DATETIME NOT NULL,
  `price_end_date` DATETIME NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`price_id`),
  CONSTRAINT `price_id_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Photo` (
  `product_photo_id` INT NOT NULL,
  `filename` VARCHAR(50) NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`product_photo_id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC),
  INDEX `product_photo_product_id_idx` (`product_id` ASC),
  INDEX `product_photo_user_id_idx` (`user_id` ASC),
  CONSTRAINT `product_photo_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_photo_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
